### ISSUE TITLE
Finish exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s1-evaluacion-intermedia-joanajimfer#1]
Good job @joanajimfer  !!
Here you have some tips to improve the exercise

- [x] index.html should be on the root of the project
- [x] Organize CSS and images in folders
- [x] Avoid absolute routes to link CSS and images
- [x] Publish it on Github Pages and add the link next to repo description
- [x] Improve meta title
- [x] Add an h1
- [x] Add a link on the logo
- [x] Menu items should be anchors
- [x] Avoid uppercase on HTML, we can transform the text with CSS
- [x] Avoid element selector as `header`, let's use a class instead!
- [x] Be careful with CSS syntax,  `10 px` shouldn't have spaces -> `10px`

Once you have those fixed try to finish the styles. 
Start with the mobile version of the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: **reset browser styles**, center content, add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

Let me know if you have any doubts ;)

**Comment by joanajimfer** [comment]
I added the changes and the responsive version, please, check it.

**Comment by joanajimfer** [comment]
> I added the changes and the responsive version, please, check it.

**Comment by nasivuela** [comment]
Cool @joanajimfer !!!

I have reopened the issue since there is still a couple of points to be fixed:

- Avoid absolute routes to link CSS and images. -> We still need to fix the logo route,  the image is broken on Github Pages.

- Menu items should be anchors. -> Every menu item should be a link, we can leave the `href` empty at the moment since we do not know where to link yet.

And here you have new improvements to make this an excellent work:

- [ ] Indent the code to improve readability and to avoid bugs!
- [ ] Font CSS link should be before your main CSS
- [ ] According to the PDF with the specifications, the menu text weight is thinner.
- [ ] Be careful with the width for the main title, on desktop version is too narrow and it pushes the word 'Diversidad' to the right.

Go for it!

**Comment by joanajimfer** [comment]
Hello @nasivuela , I corrected the points, please, check it know.

**Comment by nasivuela** [comment]
Check again the width of the main title on desktop ;)
